In [28]:
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn.preprocessing import LabelEncoder

In [36]:
data = pd.read_csv('smartphones_ready_for_ml.csv')

smart_models = data.model
smart_model_MLfited = LabelEncoder().fit(smart_models)
data.model = smart_model_MLfited.transform(data.model)

sim = data.sim
sim_MLfited = LabelEncoder().fit(sim)
data.sim = sim_MLfited.transform(data.sim)

os = data.os
os_MLfited = LabelEncoder().fit(os)
data.os = os_MLfited.transform(data.os)


In [37]:
data = data.iloc[:, 1:]

In [44]:
SMARTPHONES = data.model
del data['model']


In [50]:
data.head()

price  rating  cores num  sim  processor  inbuilt memory  ram  battery  \
0  61048.89    89.0          8    1        3.2             256   12     5000   
1  22187.79    81.0          8    3        2.2             128    6     5000   
2  18313.89    75.0          8    3        2.4              64    4     5000   
3  16648.89    81.0          8    3        2.2             128    6     5000   
4  27748.89    82.0          8    3        2.6             128    6     5000   

   fast charging (w)  display size (inch)  display heigth (px)  \
0              100.0                 6.70                 3216   
1               33.0                 6.59                 2412   
2               15.0                 6.60                 2408   
3                0.0                 6.55                 2400   
4               67.0                 6.70                 2412   

   display width (px)  display frequancy (hz)  rear num  rear camera (max mp)  \
0                1440                     120         3                  50.0   
1                1080                     120         3                  64.0   
2                1080                      90         3                  50.0   
3                1080                     120         3                  50.0   
4                1080                     120         3                 108.0   

   front num  front camera (max mp)  card_value (gb)  os  
0          1                   16.0                0   7  
1          1                   16.0             1024   5  
2          1                   13.0             1024   7  
3          1                   16.0             1024   5  
4          1                   16.0                0   7

In [75]:
clear_data = data.columns
clear_data = np.array(clear_data)
clear_data = np.array(['price', 'ram', 'battery', 'display size (inch)', 
                       'rear camera (max mp)','front camera (max mp)',])
a = [pd.Series(data[x]) for x in clear_data]
clear_data = pd.DataFrame(a).T


In [84]:
clear_data.head()


price   ram  battery  display size (inch)  rear camera (max mp)  \
0  61048.89  12.0   5000.0                 6.70                  50.0   
1  22187.79   6.0   5000.0                 6.59                  64.0   
2  18313.89   4.0   5000.0                 6.60                  50.0   
3  16648.89   6.0   5000.0                 6.55                  50.0   
4  27748.89   6.0   5000.0                 6.70                 108.0   

   front camera (max mp)  
0                   16.0  
1                   16.0  
2                   13.0  
3                   16.0  
4                   16.0

In [77]:
model = KMeans(n_clusters=len(clear_data)).fit(clear_data)

C:\Users\bigbl\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
C:\Users\bigbl\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1382: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=4.
  warnings.warn(
C:\Users\bigbl\AppData\Local\Temp\ipykernel_8848\952284885.py:1: ConvergenceWarning: Number of distinct clusters (944) found smaller than n_clusters (968). Possibly due to duplicate points in X.
  model = KMeans(n_clusters=len(clear_data)).fit(clear_data)


In [103]:
labels = model.labels_
labels = [x for x in labels]
labels.index(147)

734

In [106]:
test = clear_data.iloc[0].array

test

<NumpyExtensionArray>
[59342.0, 12.0, 5000.0, 6.7, 50.0, 16.0]
Length: 6, dtype: float64

In [110]:
ans = model.predict([test])
ans

C:\Users\bigbl\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but KMeans was fitted with feature names
  warnings.warn(


array([147])

In [112]:
labels.index(ans)

734

In [114]:
smart_model_MLfited.inverse_transform([734])

array(['vivo t1x (6gb ram + 128gb)'], dtype=object)

In [5]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LinearRegression

In [2]:
data = load_iris()

In [7]:
X, y = data['data'], data['target']

In [8]:
X, y

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [28]:
model = LinearRegression()
model.fit(X, y)

LinearRegression()

In [32]:
model.predict(X[:10])

array([-0.08254936, -0.04012845, -0.04862768,  0.01229986, -0.07536672,
        0.05829101,  0.03833672, -0.04448632,  0.01983243, -0.0821971 ])

In [31]:
y[123]

2